version: '3'

services:
  php:
    build: docker/php
    container_name: loyality_service_php
    restart: always
    expose:
      - '9001'
    depends_on:
      - database
    volumes:
      - ./:/app:cached
      - ./var/log:/var/log
  nginx:
    build: docker/nginx
    restart: always
    container_name: loyality_service_web
    ports:
      - 81:80
    depends_on:
      - php
      - database
    volumes:
      - ./:/app:cached
      - ./var/log/nginx:/var/log/nginx
  database:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:

